# Generated by Django 5.1.7 on 2025-03-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feast', '0005_alter_order_order_date_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('canteen_owner', 'Canteen Owner'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
