# Generated by Django 5.1.7 on 2025-04-01 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feast', '0007_remove_order_total_price_rename_user_customuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='feast.customuser'),
        ),
    ]
