# Generated by Django 5.1.7 on 2025-04-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_alter_logentry_user'),
        ('feast', '0010_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
