# Generated by Django 5.1.7 on 2025-04-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feast', '0011_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
