# Generated by Django 5.1.7 on 2025-04-03 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feast', '0015_rename_user_type_user_user_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='USER_TYPES',
            new_name='user_type',
        ),
    ]
